SELECT 
	TITLE AS title
	, SITE_URL AS siteUrl
FROM (
	SELECT * 
	FROM TB_SEARCH_DATA 
	WHERE UPPER(BODY) LIKE '%java%'
	ORDER BY SCORE DESC
	LIMIT 0, 10
) T1
	
	
	SELECT * FROM TB_SEARCH_DATA WHERE UPPER(TITLE) IN ( 'LINUX' )
	
	
	SELECT SUBSTR(BODY, INSTR(BODY, 'heal')-50, LENGTH('heal')+100) FROM TB_SEARCH_DATA
	
	
	SELECT COUNT(*) AS totalCount  FROM TB_SEARCH_DATA   WHERE 1 = 1  AND UPPER(TITLE) IN ( 'JAVA' ) AND UPPER(HEAD) IN ( 'JAVA' ) AND UPPER(BODY) IN ( 'JAVA' )  LIMIT 0, 10
	
	SELECT COUNT(*) AS totalCount  FROM TB_SEARCH_DATA   WHERE 1 = 1  AND UPPER(TITLE) IN ( 'JAVA' ) AND UPPER(HEAD) IN ( 'JAVA' ) AND UPPER(BODY) IN ( 'JAVA' )